### ISSUE TITLE
Today's update: Terminal.app in my mac in not borderless

### ISSUE THREAD

**Issue by chishui** [jasonwoodland/iTerm2-borderless#1]
Hi, 

I fetched your recently code, but found Terminal.app was not borderless. Could you check it?

Thanks,

**Comment by jasonwoodland** [comment]
Try going to Preferences > Profiles > Window and make sure "Style" in the bottom right is set to "No Title Bar". You'll have to close and reopen a window to see the changes.

**Comment by chishui** [comment]
Hey, it works with today's commits, thank you so much
