### ISSUE TITLE
No text padding

### ISSUE THREAD

**Issue by yamini-krishnamurthy** [jasonwoodland/iTerm2-borderless#10]
Hello, so I initially had iTerm2 installed but I didn't want any of my profiles anymore so I uninstalled it and just used the iTerm2 given in the iTerm2-borderless folder. I dragged it to my Applications and this is what I got. Any idea why there's no text padding?

<img width="573" alt="screen shot 2018-05-29 at 7 57 18 am" src="https://user-images.githubusercontent.com/32017567/40635084-f5edb1a8-6315-11e8-9f2c-581f02a330d9.png">

**Comment by jasonwoodland** [comment]
Set the margins in Preferences > Advanced
![screen shot 2018-05-29 at 12 36 29 pm](https://user-images.githubusercontent.com/5356544/40635352-ef9cdb68-633c-11e8-8a70-1b76e13aae32.png)

**Comment by yamini-krishnamurthy** [comment]
Doh. Thanks!
