### ISSUE TITLE
Does not look the same

### ISSUE THREAD

**Issue by Sangwoo1** [jasonwoodland/iTerm2-borderless#11]
![image](https://user-images.githubusercontent.com/24531671/41822104-8d31ed44-7825-11e8-96ca-b03e0d3530d7.png)

Hello, I followed your instructions and everything was a success but it looks very weird. Any help is appreciated!

**Comment by jasonwoodland** [comment]
Preferences > Appearance, then disable 'Show line under title bar when the tab bar is not visible'
Preferences > Advanced, and search for "margin" to set margins under general, then search for "borderless" to set stuff I've added.
