### ISSUE TITLE
Error on start on Mojave

### ISSUE THREAD

**Issue by karambaq** [jasonwoodland/iTerm2-borderless#12]
report:
https://pastebin.com/5wszV4aR

**Comment by jasonwoodland** [comment]
Did you build it in Mojave? Try moving your preferences file, open apple's Terminal.app, enter
`mv ~/Library/Preferences/com.googlecode.iterm2.plist ~`
to move your iTerm prefs to your home, then try starting iTerm2.app again.

If that didn't fix it move your prefs back with
`mv ~/com.googlecode.iterm2.plist ~/Library/Preferences`

also there's a problem with Mojave's new window drawing routines which breaks the title bar hack in this patch.

**Comment by karambaq** [comment]
I run your build, will try you answer little bit later

**Comment by jasonwoodland** [comment]
Your right, my build doesn't work on Mojave, however I built it on my other machine with Mojave and runs fine, so either patch and build it yourself, or I'll have to push my new build.
