### ISSUE TITLE
Border showing when transparency is enabled

### ISSUE THREAD

**Issue by thatpix3l** [jasonwoodland/iTerm2-borderless#13]
Hello again!
I assume this is a bug with this patch, but when I go to the iTerm2 Preferences -> Profiles -> Window Tab and enable transparency, the border ends up showing and not transparent.
The image I have below will show what I mean.

![screen shot 2018-07-18 at 1 02 40 pm](https://user-images.githubusercontent.com/37268984/42896436-ddc478ae-8a8a-11e8-9098-838cb26fb350.png)

A quick note, don't worry about the white glow around the edges, when I took the screenshot, it added it by itself.

**Comment by jasonwoodland** [comment]
Probably can't do anything about this since the opacity is handled inside the terminal view which isn't part of the title view. You'd have to change heaps of internal geometry to get it to work properly and I just don't have enough time to spend it on this.

**Comment by thatpix3l** [comment]
Well that stinks, thank you for explaining the problem to me anyway.
I'll close this issue then.
