### ISSUE TITLE
Tabs issue

### ISSUE THREAD

**Issue by CopperGiraffe** [jasonwoodland/iTerm2-borderless#15]
I'm currently using the last version [here](https://github.com/jasonwoodland/iTerm2-borderless/releases/tag/v3.2.4beta3), but I can't get Tabs working!
Regardless their position (left, top or right) I can't get them right. (They are not rendered correctly (or at all))

I also tried with previous version and couldn't get them to work.. (The 3 last)
Currently on Mojave, I'm using your patch on High Sierra without any issues on my other computer

Beside that, thanks for the great work :)

**Comment by jasonwoodland** [comment]
Hey, it’s intended that the tab bar is hidden and you use the keyboard shortcuts mentioned in #5.

I do plan to improve the drawing of tabs in the future but it would take some work.

**Comment by CopperGiraffe** [comment]
I noticed that they were still available but with no visual feedback indeed! I just need to get used to it in the mean time, not a problem.

**Comment by jasonwoodland** [comment]
Hey @ChinesePeanuts I made a [branch](https://github.com/jasonwoodland/iTerm2-borderless/tree/wip/tabs) to get tabs working. You can apply the patch yourself or I can upload my build.

**Comment by jasonwoodland** [comment]
Added.
