### ISSUE TITLE
Crashes with "Library Not Loaded Errors"

### ISSUE THREAD

**Issue by thatpix3l** [jasonwoodland/iTerm2-borderless#16]
Although I did find a hacky solution for it, I don't really know how to make a PR for this since you applied the patches yourself and released the binary.

The solution is to download the official, stable release of iTerm, go to the **iTerm2/Contents/Frameworks** folder, copy everything inside of it, and paste into the same Frameworks folder in your patched version.

**Comment by jasonwoodland** [comment]
Should be fixed in the [latest release](https://github.com/jasonwoodland/iTerm2-borderless/releases/latest). Let me know how it goes.
