### ISSUE TITLE
Keeps crashing on open

### ISSUE THREAD

**Issue by yamini-krishnamurthy** [jasonwoodland/iTerm2-borderless#17]
I cannot open iTerm2 without it crashing.

<img width="884" alt="screen shot 2018-11-08 at 11 15 12 am" src="https://user-images.githubusercontent.com/32017567/48211523-a7ab3a80-e347-11e8-8474-acbac1b99985.png">

This happened after I updated to MacOS Mojave

**Comment by jasonwoodland** [comment]
Did you update to the [latest release](https://github.com/jasonwoodland/iTerm2-borderless/releases/latest)? If you built it yourself on High Sierra or earlier you'll need to build it again for Mojave. It could also be your iTerm2 preferences which we discovered in #7, in which case you'd need to delete `~/Library/Preferences/com.googlecode.iterm2.plist` and start over.

Let me know how it goes.

**Comment by ricardo-lobo** [comment]
I'm having the same issue with the latest release. App doesn't start. Just crashes. I deleted the plist as mentioned

**Comment by jasonwoodland** [comment]
@ricardo-lobo you're on the latest release and running Mojave?

**Comment by ricardo-lobo** [comment]
> @ricardo-lobo you're on the latest release and running Mojave?

Yes and yes. Downloaded the latest release from this repo.

**Comment by jasonwoodland** [comment]
@ricardo-lobo hmm I think I published a bad build since it didn't work for me either.
Could you try the latest build? [v3.2.6beta3](https://github.com/jasonwoodland/iTerm2-borderless/releases/tag/v3.2.6beta3)

**Comment by ricardo-lobo** [comment]
> @ricardo-lobo hmm I think I published a bad build since it didn't work for me either.
> Could you try the latest build? [v3.2.6beta3](https://github.com/jasonwoodland/iTerm2-borderless/releases/tag/v3.2.6beta3)

Working fine now
