### ISSUE TITLE
App crashing 

### ISSUE THREAD

**Issue by Ivanknmk** [jasonwoodland/iTerm2-borderless#18]
I'm on High Sierra. Already tried the latest release and also deleting the .plist file as explained in #17.

Don't know if it help but here's the problem report:

https://gist.github.com/Ivanknmk/0fcc9f5a90d3e96ad5ba02049e6ef1bc

Let me know if you need more info.

**Comment by Ivanknmk** [comment]
I just built the project without the patch and got the same error. The app doesn't crash tho.

**Comment by jasonwoodland** [comment]
Mojave changed how windows were drawn and this patch does some things against those changes.
I just added a check to the lines which I think are causing it. I can upload a build with the check if you want to try?

**Comment by Ivanknmk** [comment]
@jasonwoodland I don't have mojave but I can try, yes.

**Comment by jasonwoodland** [comment]
Here’s the patch file if you wanted to patch the source yourself: [it2b-wip.patch.txt](https://github.com/jasonwoodland/iTerm2-borderless/files/2608206/it2b-wip.patch.txt)
Here’s the patched build: [iTerm2.app.zip](https://github.com/jasonwoodland/iTerm2-borderless/files/2608203/iTerm2.app.zip)

**Comment by Ivanknmk** [comment]
@jasonwoodland it does work now but looks kind of weird. Had to patch myself as the build didn't work.

<img width="597" alt="screen shot 2018-11-26 at 12 33 41 pm" src="https://user-images.githubusercontent.com/1672248/48994816-b4b58f80-f177-11e8-8009-36e5d5ed00c2.png">

Is this the expected behavior?

**Comment by jasonwoodland** [comment]
Wow nope, I guess because I only patched the window styling for Mojave, probably to do with one of the source files in PSMTabBarControl. If you wanted to have a look around, all my changes are commented with `PATCH:` so you can see how I've changed things. 

I haven't got a copy of Sierra running so your best bet is use one of the old releases, or patch files from previous commits until you can upgrade.

**Comment by Ivanknmk** [comment]
Will do that. Closing now. I appreciate all the help.

Thanks!
