### ISSUE TITLE
tabbar always show

### ISSUE THREAD

**Issue by FE-Sakamoto** [jasonwoodland/iTerm2-borderless#19]
my iterm2 tarbar always show, even I disable "show tab bar even when there is only one tab"
but it can hide after enter fullscreen and exit fullscreen
<img width="762" alt="2018-11-28 3 58 08" src="https://user-images.githubusercontent.com/15774890/49137158-95109980-f326-11e8-8449-d2037569ec7e.png">

**Comment by jasonwoodland** [comment]
Are you on the latest release? And are you on Mojave?

**Comment by FE-Sakamoto** [comment]
YES, YES.

**Comment by FE-Sakamoto** [comment]
<img width="762" alt="2018-11-29 11 26 13" src="https://user-images.githubusercontent.com/15774890/49197397-af4f8380-f3c9-11e8-877d-5c828bc56f82.png">

**Comment by jasonwoodland** [comment]
Could you try deleting your prefs?
Just move `~/Library/Preferences/com.googlecode.iterm2.plist` and restart iTerm

**Comment by FE-Sakamoto** [comment]
I have try this before, but it dosn't work for me.

**Comment by jasonwoodland** [comment]
What does it look like after you’ve removed your prefs? Note I don’t think iTerm can be open when moving prefs because I think it might just rewrite them.

**Comment by FE-Sakamoto** [comment]
iTerm can open, but it will show the Crash Report, And require the full disk Access, Then the plist file will create at same path.

**Comment by jasonwoodland** [comment]
Ahh I think I figured it out. Setting it to light or minimal gave me similar results to what you've shown me. Try setting it to Dark.
<img width="1008" alt="screen shot 2018-12-04 at 1 38 20 am" src="https://user-images.githubusercontent.com/5356544/49380234-49fee800-f765-11e8-9aa2-fca358133e72.png">

**Comment by FE-Sakamoto** [comment]
`Minimal`

![Minimal](https://ws4.sinaimg.cn/large/006tNbRwgy1fxufjkp3bsj316u0u0agm.jpg)

`Light`

![Light](https://ws2.sinaimg.cn/large/006tNbRwgy1fxufjr5cdmj31850u07bi.jpg)

`Dark`

![Dark](https://ws2.sinaimg.cn/large/006tNbRwgy1fxufjq3hrdj316q0u0dmy.jpg)

`after enter fullscreen`

![after enter fullscreen](https://ws1.sinaimg.cn/large/006tNbRwgy1fxufjozorlj31650u07as.jpg)

**Comment by jasonwoodland** [comment]
Thanks for the shots. The 'after enter fullscreen' is a bug I gotta fix.

Just to clarify, you did just download the [latest release](https://github.com/jasonwoodland/iTerm2-borderless/releases/tag/v3.2.6beta3)? It looks like it's been patched but hunks have failed.

If it's the latest release, can I get you to try my prefs out? (This creates a backup of your current prefs just in case)
```
git clone --depth=1 https://github.com/jasonwoodland/iTerm2-borderless.git
cd iTerm2-borderless
cp ~/Library/Preferences/com.googlecode.iterm2.plist com.googlecode.iterm2.plist~`date +%s`
cp com.googlecode.iterm2.plist ~/Library/Preferences/com.googlecode.iterm2.plist
```
Then restart iTerm.

**Comment by FE-Sakamoto** [comment]
it works! thx.

**Comment by jasonwoodland** [comment]
Strange man… wondered what setting it was causing it 🤔

**Comment by FE-Sakamoto** [comment]
tabbar title can't show complete.
<img width="682" alt="2018-12-26 3 58 52" src="https://user-images.githubusercontent.com/15774890/50438153-ae0d6a00-0927-11e9-8fb5-bf0ea10e3113.png">

<img width="682" alt="2018-12-26 4 01 24" src="https://user-images.githubusercontent.com/15774890/50438082-743c6380-0927-11e9-9a9f-bb64ace81e49.png">
