### ISSUE TITLE
Cannot display scroll back contents

### ISSUE THREAD

**Issue by hguandl** [jasonwoodland/iTerm2-borderless#20]
Hi, in the [latest release](
https://github.com/jasonwoodland/iTerm2-borderless/releases/tag/v3.2.6beta3), I found that if I scroll back, the contents were not displayed. And if I select the blank position, the text appeared. Do you have any ideas about that?

![](https://user-images.githubusercontent.com/10684225/49349762-1e3d1d00-f6e7-11e8-9ed9-88ce39b7aff4.png)
![](https://user-images.githubusercontent.com/10684225/49349778-34e37400-f6e7-11e8-9140-ad40c85ff005.png)
![](https://user-images.githubusercontent.com/10684225/49349790-43319000-f6e7-11e8-9998-f644ab6b3b72.png)

**Comment by jasonwoodland** [comment]
Is GPU rendering enabled in Preferences > General? I think I've witnessed this on my MBA recently when not connected to power.

**Comment by hguandl** [comment]
Yes it has been enabled.

<img width="814" alt="2018-12-04 00 52 01" src="https://user-images.githubusercontent.com/10684225/49388426-e70a5280-f75e-11e8-930e-a60c60e163a2.png">

I unchecked "Disable GPU renderer when disconnected from power" but the problem was still there.

**Comment by jasonwoodland** [comment]
I think there’s a an advanced setting which can also disable GPU rendering.

Have a search under advanced or you can try my prefs:

```
git clone --depth=1 https://github.com/jasonwoodland/iTerm2-borderless.git
cd iTerm2-borderless
cp ~/Library/Preferences/com.googlecode.iterm2.plist com.googlecode.iterm2.plist~`date +%s`
cp com.googlecode.iterm2.plist ~/Library/Preferences/com.googlecode.iterm2.plist
```

Then restart iTerm

**Comment by hguandl** [comment]
Perhaps I have found the problem. If I enable the transparency of the window, the issue would appear. The transparency is such a troublesome function that now maybe I should simply forget about that.

**Comment by jasonwoodland** [comment]
Oh you're right. I suppose you could use tmux and let that handle the scroll buffer if you really liked having transparency.

**Comment by JChouCode** [comment]
What was the solution to this issue? Disabling transparency doesn't seem to fix it for me. Neither does using your preferences.

**Comment by jasonwoodland** [comment]
Are you on a MacBook? Could be the GPU renderer being disabled? Even I think I had this setting enabled in my prefs by accident, it should be unchecked. (Preferences > General > Advanced GPU Settings > Disable GPU renderer when disconnected from power)
<img width="882" alt="screen shot 2018-12-09 at 12 44 36 pm" src="https://user-images.githubusercontent.com/5356544/49692493-34981c80-fbb0-11e8-9ee0-41bdc51941ff.png">
