### ISSUE TITLE
Quits unexpectedly

### ISSUE THREAD

**Issue by JChouCode** [jasonwoodland/iTerm2-borderless#21]
It quits the second I open it. I didn't use the patch, I used the latest release.

**Comment by jasonwoodland** [comment]
Can you try the latest release I just [published](https://github.com/jasonwoodland/iTerm2-borderless/releases/tag/v3.2.6beta4)? Probably was a codesigning issue so I disabled it on this build.

**Comment by JChouCode** [comment]
It works now 👍 , do you notice that after using terminal for a bit, if you try to scroll up, the text doesn't show? It just shows a blank terminal. If I highlight the area the text reappears again. Not sure what the cause is.

**Comment by JChouCode** [comment]
It works 👍

**Comment by jasonwoodland** [comment]
😅
