### ISSUE TITLE
tab border visible

### ISSUE THREAD

**Issue by yamini-krishnamurthy** [jasonwoodland/iTerm2-borderless#23]
Hi,

I have this ugly border around my tab and I can't figure out how to make it go away.

<img width="1399" alt="Screen Shot 2019-04-07 at 1 38 36 PM" src="https://user-images.githubusercontent.com/32017567/55687434-ec5cf100-593a-11e9-9480-7c4b25a510b0.png">

**Comment by jasonwoodland** [comment]
Are you running the latest [release](https://github.com/jasonwoodland/iTerm2-borderless/releases) or did you patch yourself? Could you share your `~/Library/Preferences/com.googlecode.iterm2.plist`

**Comment by yamini-krishnamurthy** [comment]
I am, looks like the problem just went away. Thanks though!

**Comment by jasonwoodland** [comment]
No probs
