### ISSUE TITLE
Question: Post-install Auto-updates

### ISSUE THREAD

**Issue by rjhilgefort** [jasonwoodland/iTerm2-borderless#3]
I've been using for a bit now, and the iTerm auto-updates are popping up. Are we able to update through the auto updates, or should we skip new versions and favor a new install from this repo. I guess what I'm asking is, is the patching process stable enough that if the update breaks my install, that I could patch the newly updated iTerm with consistency.

I love this build of iTerm and just want to make sure I don't lose the extra real estate and ascetics through an update. Thanks for the repo!

**Comment by jasonwoodland** [comment]
Hey, sadly updates overwrite the changes. But I try to update the patch each time I get notified of an update. You can try patching the latest version yourself (see readme) and just replace the app in your Applications. It won't overwrite your prefs. 

Also, if a patch ever fails please let me know so I can push a fixed patch.

**Comment by rjhilgefort** [comment]
Thanks for the response. Would it make sense to keep the README updated with the last iTerm version/build that was patched? That would at least give people some idea what the update status is at a quick glance.

**Comment by jasonwoodland** [comment]
Good idea I'll do that next time I push
