### ISSUE TITLE
Can't run Terminal.app in the repo

### ISSUE THREAD

**Issue by chishui** [jasonwoodland/iTerm2-borderless#4]
Hi, 
just pulled the repo and cannot open Terminal.app in the repo.
My Mac version is: 10.12.6, it's just updated today. It had been working well before I updated my macOS and pulled the repo.

**Comment by jasonwoodland** [comment]
Hey I just checked by going:
`git clone https://github.com/jasonwoodland/iTerm2-borderless.git`
and opening the Terminal.app from Finder and was working for me.

You did use `git clone` and not download the zip from GitHub?

Try running the bin from the command line like so:
`git clone https://github.com/jasonwoodland/iTerm2-borderless.git && ./iTerm2-borderless/Terminal.app/Contents/MacOS/iTerm2`

Let me know if it crashes.

Thanks

**Comment by chishui** [comment]
Sorry, my mistake. It works now, have no idea why it didn't work before. I'm closing this issue.
