### ISSUE TITLE
Tab bar visible

### ISSUE THREAD

**Issue by tomaskallup** [jasonwoodland/iTerm2-borderless#6]
Hi, I love your patch, it completely changed the way I use my terminal.

However I seem to be having trouble, images didn't work for me, so I tried a few things:
- Reinstalling your patched iTerm
- Installing unpatched iTerm
- Patching it myself

In the end I got it working, I removed all iTerm installations & configurations and downloaded your patch once again. Images did work, but for some reason tab bar is now visible.

<img width="973" alt="screen shot 2018-01-28 at 14 21 46" src="https://user-images.githubusercontent.com/26621166/35482570-b06618e2-0437-11e8-85c2-9dc1aed600a1.png">

Do you have any idea what cloud cause this and how to fix it?

**Comment by jasonwoodland** [comment]
Hey I just pushed a fresh build. If it's still there, try closing iTerm, copying over my config, and then open iTerm again. Also if you're building from sources, I updated the `xcodebuild` command to run in the README steps. Let me know how it goes!

**Comment by tomaskallup** [comment]
I think I might know what's the issue. Is it possible that having default iTerm2 and your Terminal running simultaneously could mess something up? I downloaded your updated build, ran it and it was fine, no top bar, no tab bar but after closing it (Cmd + Q) and running it again, it broke and went to default iTerm settings. 
I'll try to experiment some more with it, right now I'm using self patched iTerm2 built from source and that seems to work, but my best guess is I messed something up in my system which is causing your patch to act all funny.

Anyways, sorry for the hold up and thanks for your response!

**Comment by tomaskallup** [comment]
Okay, I was able to resolve it, I didn't move your build into Applications so after first run it created its own config folder.

Anyways I still have couple issues:
- first one is "ghost terminal", meaning I see some old session commands and their output underneath the terminal
- second one, imgcat and others for some reason do not work, eventhough the image seems to occupy its space, it's invisible

Attaching a screenshot - on the left is your build, on the right side is my custom patched
![screen shot 2018-02-28 at 12 25 02 2](https://user-images.githubusercontent.com/26621166/36785392-ee6c2204-1c82-11e8-803e-763d0009502f.png)

**Comment by jasonwoodland** [comment]
That ghosting is pretty weird, my terminal is opaque so I've never experienced that. Also, imgcat doesn't work for me either, although if I click and drag over the occupied area I can drag the image around. I'll play around and try and fix these.

**Comment by jasonwoodland** [comment]
So that ghosting only occurs when `WINDOW_TYPE_NO_TITLE_BAR` is set and the window shadow is forced on, which is what the patch does in PseudoTerminal.m:
```
--- 638,644 ----
          [myWindow setFrame:initialFrame display:NO];
      }
  
!     [myWindow setHasShadow:YES]; // PATCH: (Modified) Native macOS window shadow
```
Maybe you could increase the window's blur radius in preferences, that makes it less noticeable.
Or if you keep your terminals taking up most of the screen you could probably just use the vanilla iTerm2 without the window shadows.

**Comment by tomaskallup** [comment]
I can live without the shadow, so I can remove that. Main issue is the imgcat, for that I have one note. When I tried to patch the terminal myself, I couldn't see images when using the `master` branch of iterm. Right now my iterm is on build 3.1.0 where the images work fine, so maybe something changed.
