### ISSUE TITLE
Patched version of iTerm2 crashing

### ISSUE THREAD

**Issue by thatpix3l** [jasonwoodland/iTerm2-borderless#7]
Title, after correctly patching the app, it crashes immediately.
I have this crash report if this helps:
https://pastebin.com/9KW7vKGK

**Comment by jasonwoodland** [comment]
That’s strange. Did you try running my build?

**Comment by thatpix3l** [comment]
Yes, I did try running the already-packaged build from the "iTerm2-borderless/Terminal.app"
Although one question, why is it named "Terminal.app"?
Shouldn't it be "iTerm2.app"?
I don't know if this can cause problems because of the macOS shipped "Terminal.app"

**Comment by jasonwoodland** [comment]
I used to bundle an icon with this patch and change the menubar to resemble Terminal.app and so it was just named Terminal.

It might be your preferences, I clicked around in mine but couldn't trigger it to crash. 
Could you send me yours? Its found under `~/Library/Preferences/com.googlecode.iterm2.plist`

**Comment by thatpix3l** [comment]
Uploaded it here
[com.googlecode.iterm2.plist.zip](https://github.com/jasonwoodland/iTerm2-borderless/files/2031495/com.googlecode.iterm2.plist.zip)
And it doesn't crash after click around, it crashes at launch with the patch.

iTerm2 works by it self when I re-download the git source in a different directory and just building it plain.

**Comment by jasonwoodland** [comment]
Yep it's your prefs

**Comment by jasonwoodland** [comment]
I couldn't find what setting in your plist is causing this to happen but it does differ a lot from mine

**Comment by thatpix3l** [comment]
It seems to work-ish now.
I just deleted the preferences file, and just now ran the patched iTerm2.app
It works now!
Although it creates this weird grey line
![screen shot 2018-05-23 at 10 35 44 am](https://user-images.githubusercontent.com/37268984/40431255-0efb3530-5e75-11e8-8b31-46ccff4df18b.png)
But this a different issue, so I guess you can close this one for this problem?

**Comment by jasonwoodland** [comment]
Uncheck "show line under titlebar when the tab bar is not visible": (bottom right)
![screen shot 2018-05-24 at 12 38 09 am](https://user-images.githubusercontent.com/5356544/40431436-c6bc1dd6-5eea-11e8-8df1-0d995bca0e23.png)

And set your margins under advanced:
![screen shot 2018-05-24 at 12 39 29 am](https://user-images.githubusercontent.com/5356544/40431521-f1246524-5eea-11e8-908a-cd5628f1936c.png)

**Comment by thatpix3l** [comment]
That fixed it, thank you!
![screen shot 2018-05-23 at 10 50 15 am](https://user-images.githubusercontent.com/37268984/40432195-1b60b6ae-5e77-11e8-8948-c4f9077d427d.png)
I guess the real problems was me not reading the README
Sorry for all of this confusion.
I think it would be nice if maybe these new "Margin Settings" can be more explicitly shown in the README so others might not run into the same issue? But otherwise, a transparent titlebar!
THANK YOU!

**Comment by jasonwoodland** [comment]
No worries, and good idea, plus theres a lot of preferences I should just flat out disable with the patch so they don't break the look. Cheers
