### ISSUE TITLE
Try to launch Terminal.app and it crashed

### ISSUE THREAD

**Issue by karambaq** [jasonwoodland/iTerm2-borderless#8]
There is a report:
https://pastebin.com/YhMwJMQb

**Comment by thatpix3l** [comment]
I had the exact same problem, and jasonwoodland (creator of this repo) helped me here: #7 

TL;DR You have to delete your already existing iTerm2 preferences file in ~/Library/Preferences/com.googlecode.iterm2.plist (make sure to back it up somewhere safe first!)
You will have to re-create your preferences once you open back up the patched Terminal.app

**Comment by karambaq** [comment]
@HandsomePixel unfortunately, that doesn't help :(

**Comment by jasonwoodland** [comment]
Can you try running the `xcodebuild` command on another unpatched clone? It says there isn’t a library loaded so something else could be wrong.
```
Dyld Error Message:
  Library not loaded: @rpath/CoreParse.framework/Versions/A/CoreParse
  Referenced from: /Users/USER/*/Terminal.app/Contents/MacOS/iTerm2
  Reason: image not found
```

**Comment by karambaq** [comment]
@jasonwoodland It's says
`xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance`

**Comment by jasonwoodland** [comment]
Actually after looking at iTerm2 looks like they forgot to add `CoreParse.framework`, but it's fixed now https://github.com/gnachman/iTerm2/commit/0c81cf203ead3fe76c65f79d3af7834b9d24e5c1

But I just pushed a new build so it should work now!

**Comment by karambaq** [comment]
@jasonwoodland Thanks, it works now!
