### ISSUE TITLE
Is there a way to hide title status?

### ISSUE THREAD

**Issue by karambaq** [jasonwoodland/iTerm2-borderless#9]
My previous setup looks like this:
<img width="970" alt="2018-05-25 23 16 24" src="https://user-images.githubusercontent.com/14233969/40564690-487208da-6072-11e8-9add-2fab56ce8b8f.png">

And current with you fork:
<img width="970" alt="2018-05-25 23 19 53" src="https://user-images.githubusercontent.com/14233969/40564704-53652240-6072-11e8-9a60-86362a8c64b4.png">

Is there a way to hide this 'Terminal - ' in title?

**Comment by jasonwoodland** [comment]
Just added some extra options under *Advanced* in Preferences in 62965e3 so go ahead and try the new build/patch out
![screen shot 2018-05-26 at 5 47 31 pm](https://user-images.githubusercontent.com/5356544/40573955-e5440e20-610c-11e8-96fe-b4fe4ab7924b.png)

**Comment by karambaq** [comment]
@jasonwoodland Awesome, thanks!

**Comment by jasonwoodland** [comment]
No worries man
